package com.kdnakt.leetcode;

import java.util.Arrays;

/**
 * You are given two strings s and t.
 * 
 * String t is generated by random shuffling string s
 * and then add one more letter at a random position.
 * 
 * Return the letter that was added to t.
 * 
 * Constraints:
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lower-case English letters.
 */
public class Solution {

    public char findTheDifference(String s, String t) {
        if (s.length() == 0) return t.charAt(0);
        char[] sarr = s.toCharArray();
        char[] tarr = t.toCharArray();
        Arrays.sort(sarr);
        Arrays.sort(tarr);
        return tarr[Arrays.mismatch(sarr, tarr)];
    }

}
